In [83]:
import plotly
import plotly.figure_factory as ff
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import pandas as pd

df_buildings = pd.read_csv('buildings.csv')
df_energy = pd.read_csv('energy_billing.csv')

In [84]:
df_buildings.head()
df_buildings.rename(columns={'Bl_id': 'bl_id'}, inplace=True)
df_buildings['sq_ft'] = df_buildings['sq_ft'].str.replace(',', '')
df_buildings['sq_ft'] = df_buildings['sq_ft'].astype(float)

property_type = {'Public Services, police': 1,'Education, vocational': 2,
                'Healthcare, Senior Care Community': 3, 'Healthcare, Urgent Care/Clinic/Out Patient': 4,
                'Lodging, Residential Care': 5, 'Office': 6, 'Public Assembly, Convention Center': 7,
                'Public Assembly, Museum': 8, 'Public Assembly, Other': 9, 'VACANT': 10,
                'Warehouse, self storage': 11}
df_buildings['Property Type Code'] = [property_type[item] for item in df_buildings.property_type] 

df_buildings.head()

,bl_id,name,address1,block,lot,lat,lon,sq_ft,property_type,agency_occupied,year_built,neighborhood,council_district,Property Type Code
0,B00005,DGS Public Building Maintenance Shop,500 Fallsway,1255,1,39.29588,-76.610280,18144.00,"Warehouse, self storage",DGS,1945.0,Penn - Fallsway,11.0,11
1,B00011,First Mariner Arena,201 West Baltimore St,644,1,39.28862,-76.618620,697620.00,"Public Assembly, Convention Center",Civic Centers,1960.0,Downtown,11.0,7
2,B00022,Baltimore City Mounted Police Unit,411 Fallsway St,1255,2,39.29556,-76.610280,11270.59,"Public Services, police",BCPD,NaN,Penn - Fallsway,11.0,1
3,B00026,Baltimore City Police North Western District,5271 Reisterstown Rd,4543B,27,39.34462,-76.685455,56228.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1
4,B00028,Baltimore City Police Southern District,10 Cherry Hill Rd,7610,11,39.25288,-76.617200,29314.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1

In [85]:
df_energy = df_energy[df_energy["bge_therms_used"].notnull()]
df_energy.head()

,bl_id,building_name,address,utility,account,consump_month,consump_year,bge_kWh_used,bge_therms_used
0,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,12.0,2019.0,36551.0,1173.0
1,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,12.0,2019.0,11780.0,2966.0
3,B00022,Baltimore City Mounted Police Unit,411 Fallsway St,bge,2.119590e+09,12.0,2018.0,7301.0,0.0
4,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,11.0,2019.0,33586.0,1151.0
5,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,11.0,2019.0,11420.0,2232.0

In [86]:
df_energy_2019 = df_energy[df_energy.consump_year == 2019.0]
df_energy_2018 = df_energy[df_energy.consump_year == 2018.0]
df_energy_2017 = df_energy[df_energy.consump_year == 2017.0]
df_energy_2019.head()

,bl_id,building_name,address,utility,account,consump_month,consump_year,bge_kWh_used,bge_therms_used
0,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,12.0,2019.0,36551.0,1173.0
1,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,12.0,2019.0,11780.0,2966.0
4,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,11.0,2019.0,33586.0,1151.0
5,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,11.0,2019.0,11420.0,2232.0
8,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,10.0,2019.0,38840.0,1430.0

In [87]:
df_energy_2017_sum = df_energy_2017.groupby("bl_id").sum()
df_energy_2018_sum = df_energy_2018.groupby("bl_id").sum()
df_energy_2019_sum = df_energy_2019.groupby("bl_id").sum()
df_rep_2017 = np.repeat(2017, len(df_energy_2017_sum))
df_energy_2017_sum['consump_year'] = df_rep_2017
df_rep_2018 = np.repeat(2018, len(df_energy_2018_sum))
df_energy_2018_sum['consump_year'] = df_rep_2018
df_rep_2019 = np.repeat(2019, len(df_energy_2019_sum))
df_energy_2019_sum['consump_year'] = df_rep_2019
df_energy_2019_sum.head()

,account,consump_month,consump_year,bge_kWh_used,bge_therms_used
bl_id,,,,,
B00005,3.920882e+10,28.0,2019,264236.0,11638.0
B00011,7.422829e+10,56.0,2019,2266172.0,2865.0
B00022,1.483713e+10,28.0,2019,53012.0,0.0
B00026,3.325918e+10,28.0,2019,70893.0,0.0
B00028,7.656649e+10,32.0,2019,179467.0,3985.0

In [88]:
df_energy_2017_sum["BTU electric"] = (df_energy_2017_sum["bge_kWh_used"])*3.412
df_energy_2017_sum["BTU gas"] = (df_energy_2017_sum["bge_therms_used"])*100
df_energy_2017_sum["Site BTU"] = (df_energy_2017_sum["BTU electric"] + df_energy_2017_sum["BTU gas"])
df_energy_2017_sum["Source BTU"] = (((df_energy_2017_sum["BTU electric"])*2.8) + ((df_energy_2017_sum["BTU gas"])*1.05))
df_energy_2017_sum.head()

,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,BTU electric,BTU gas,Site BTU,Source BTU
bl_id,,,,,,,,,
B00005,7.281638e+10,85.0,2017,434431.0,13496.0,1.482279e+06,1349600.0,2.831879e+06,5.567460e+06
B00011,1.424136e+11,178.0,2017,4879338.0,8278.0,1.664830e+07,827800.0,1.747610e+07,4.748443e+07
B00022,2.755467e+10,85.0,2017,97554.0,0.0,3.328542e+05,0.0,3.328542e+05,9.319919e+05
B00026,3.325918e+10,63.0,2017,26636.0,0.0,9.088203e+04,0.0,9.088203e+04,2.544697e+05
B00028,1.244205e+11,85.0,2017,396080.0,7892.0,1.351425e+06,789200.0,2.140625e+06,4.612650e+06

In [89]:
df_energy_2018_sum["BTU electric"] = (df_energy_2018_sum["bge_kWh_used"])*3.412
df_energy_2018_sum["BTU gas"] = (df_energy_2018_sum["bge_therms_used"])*100
df_energy_2018_sum["Site BTU"] = (df_energy_2018_sum["BTU electric"] + df_energy_2018_sum["BTU gas"])
df_energy_2018_sum["Source BTU"] = (((df_energy_2018_sum["BTU electric"])*2.8) + ((df_energy_2018_sum["BTU gas"])*1.05))
df_energy_2018_sum.head()

,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,BTU electric,BTU gas,Site BTU,Source BTU
bl_id,,,,,,,,,
B00005,6.721512e+10,78.0,2018,440271.0,14806.0,1.502205e+06,1480600.0,2.982805e+06,5.760803e+06
B00011,1.272485e+11,156.0,2018,3699854.0,7281.0,1.262390e+07,728100.0,1.335200e+07,3.611143e+07
B00022,2.543508e+10,78.0,2018,89450.0,0.0,3.052034e+05,0.0,3.052034e+05,8.545695e+05
B00026,5.701574e+10,78.0,2018,118189.0,0.0,4.032609e+05,0.0,4.032609e+05,1.129130e+06
B00028,1.148497e+11,78.0,2018,295602.0,7133.0,1.008594e+06,713300.0,1.721894e+06,3.573028e+06

In [90]:
df_energy_2019_sum["BTU electric"] = (df_energy_2019_sum["bge_kWh_used"])*3.412
df_energy_2019_sum["BTU gas"] = (df_energy_2019_sum["bge_therms_used"])*100
df_energy_2019_sum["Site BTU"] = (df_energy_2019_sum["BTU electric"] + df_energy_2019_sum["BTU gas"])
df_energy_2019_sum["Source BTU"] = (((df_energy_2019_sum["BTU electric"])*2.8) + ((df_energy_2019_sum["BTU gas"])*1.05))
df_energy_2019_sum.head()

,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,BTU electric,BTU gas,Site BTU,Source BTU
bl_id,,,,,,,,,
B00005,3.920882e+10,28.0,2019,264236.0,11638.0,901573.232,1163800.0,2065373.232,3.746395e+06
B00011,7.422829e+10,56.0,2019,2266172.0,2865.0,7732178.864,286500.0,8018678.864,2.195093e+07
B00022,1.483713e+10,28.0,2019,53012.0,0.0,180876.944,0.0,180876.944,5.064554e+05
B00026,3.325918e+10,28.0,2019,70893.0,0.0,241886.916,0.0,241886.916,6.772834e+05
B00028,7.656649e+10,32.0,2019,179467.0,3985.0,612341.404,398500.0,1010841.404,2.132981e+06

In [91]:
df_2019 = pd.merge(df_energy_2019_sum,
                           df_buildings,
                           on = "bl_id",
                           how = "left")
df_2019["Site EUI"] = (df_2019["Site BTU"] / df_2019["sq_ft"])
df_2019["Source EUI"] = (df_2019["Source BTU"] / df_2019["sq_ft"])
df_2019.head()

,bl_id,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,BTU electric,BTU gas,Site BTU,Source BTU,...,lon,sq_ft,property_type,agency_occupied,year_built,neighborhood,council_district,Property Type Code,Site EUI,Source EUI
0,B00005,3.920882e+10,28.0,2019,264236.0,11638.0,901573.232,1163800.0,2065373.232,3.746395e+06,...,-76.610280,18144.00,"Warehouse, self storage",DGS,1945.0,Penn - Fallsway,11.0,11,113.832299,206.481209
1,B00011,7.422829e+10,56.0,2019,2266172.0,2865.0,7732178.864,286500.0,8018678.864,2.195093e+07,...,-76.618620,697620.00,"Public Assembly, Convention Center",Civic Centers,1960.0,Downtown,11.0,7,11.494336,31.465448
2,B00022,1.483713e+10,28.0,2019,53012.0,0.0,180876.944,0.0,180876.944,5.064554e+05,...,-76.610280,11270.59,"Public Services, police",BCPD,NaN,Penn - Fallsway,11.0,1,16.048578,44.936019
3,B00026,3.325918e+10,28.0,2019,70893.0,0.0,241886.916,0.0,241886.916,6.772834e+05,...,-76.685455,56228.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1,4.301894,12.045304
4,B00028,7.656649e+10,32.0,2019,179467.0,3985.0,612341.404,398500.0,1010841.404,2.132981e+06,...,-76.617200,29314.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1,34.483230,72.763217

In [92]:
df_2018 = pd.merge(df_energy_2018_sum,
                           df_buildings,
                           on = "bl_id",
                           how = "left")
df_2018["Site EUI"] = (df_2018["Site BTU"] / df_2018["sq_ft"])
df_2018["Source EUI"] = (df_2018["Source BTU"] / df_2018["sq_ft"])
df_2018.head()

,bl_id,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,BTU electric,BTU gas,Site BTU,Source BTU,...,lon,sq_ft,property_type,agency_occupied,year_built,neighborhood,council_district,Property Type Code,Site EUI,Source EUI
0,B00005,6.721512e+10,78.0,2018,440271.0,14806.0,1.502205e+06,1480600.0,2.982805e+06,5.760803e+06,...,-76.610280,18144.00,"Warehouse, self storage",DGS,1945.0,Penn - Fallsway,11.0,11,164.396200,317.504576
1,B00011,1.272485e+11,156.0,2018,3699854.0,7281.0,1.262390e+07,728100.0,1.335200e+07,3.611143e+07,...,-76.618620,697620.00,"Public Assembly, Convention Center",Civic Centers,1960.0,Downtown,11.0,7,19.139362,51.763754
2,B00022,2.543508e+10,78.0,2018,89450.0,0.0,3.052034e+05,0.0,3.052034e+05,8.545695e+05,...,-76.610280,11270.59,"Public Services, police",BCPD,NaN,Penn - Fallsway,11.0,1,27.079629,75.822962
3,B00026,5.701574e+10,78.0,2018,118189.0,0.0,4.032609e+05,0.0,4.032609e+05,1.129130e+06,...,-76.685455,56228.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1,7.171887,20.081284
4,B00028,1.148497e+11,78.0,2018,295602.0,7133.0,1.008594e+06,713300.0,1.721894e+06,3.573028e+06,...,-76.617200,29314.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1,58.739647,121.888117

In [93]:
df_2017 = pd.merge(df_energy_2017_sum,
                           df_buildings,
                           on = "bl_id",
                           how = "left")
df_2017["Site EUI"] = (df_2017["Site BTU"] / df_2017["sq_ft"])
df_2017["Source EUI"] = (df_2017["Source BTU"] / df_2017["sq_ft"])
df_2017.head()

,bl_id,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,BTU electric,BTU gas,Site BTU,Source BTU,...,lon,sq_ft,property_type,agency_occupied,year_built,neighborhood,council_district,Property Type Code,Site EUI,Source EUI
0,B00005,7.281638e+10,85.0,2017,434431.0,13496.0,1.482279e+06,1349600.0,2.831879e+06,5.567460e+06,...,-76.610280,18144.00,"Warehouse, self storage",DGS,1945.0,Penn - Fallsway,11.0,11,156.077964,306.848545
1,B00011,1.424136e+11,178.0,2017,4879338.0,8278.0,1.664830e+07,827800.0,1.747610e+07,4.748443e+07,...,-76.618620,697620.00,"Public Assembly, Convention Center",Civic Centers,1960.0,Downtown,11.0,7,25.051032,68.066331
2,B00022,2.755467e+10,85.0,2017,97554.0,0.0,3.328542e+05,0.0,3.328542e+05,9.319919e+05,...,-76.610280,11270.59,"Public Services, police",BCPD,NaN,Penn - Fallsway,11.0,1,29.532992,82.692379
3,B00026,3.325918e+10,63.0,2017,26636.0,0.0,9.088203e+04,0.0,9.088203e+04,2.544697e+05,...,-76.685455,56228.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1,1.616313,4.525676
4,B00028,1.244205e+11,85.0,2017,396080.0,7892.0,1.351425e+06,789200.0,2.140625e+06,4.612650e+06,...,-76.617200,29314.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1,73.023980,157.353138

In [94]:
df_2017.to_csv('2017FullData.csv')
df_2018.to_csv('2018FullData.csv')
df_2019.to_csv('2019FullData.csv')

In [95]:
df_final = pd.concat([df_2017, df_2018, df_2019], axis=0)
df_final.to_csv('All3Data.csv')

In [96]:
print(len(df_2017))
print(len(df_2018))
print(len(df_2019))

34
34
33

In [97]:
df_2017_temp = df_2017[["bl_id","Source EUI", "Site EUI"]]
df_2017_temp.rename(columns={'Source EUI': 'Source EUI 2017', 'Site EUI': 'Site EUI 2017'}, inplace=True)
df_2018_temp = df_2018[["bl_id","Source EUI", "Site EUI"]]
df_2018_temp.rename(columns={'Source EUI': 'Source EUI 2018', 'Site EUI': 'Site EUI 2018'}, inplace=True)
df_2019_temp = df_2019[["bl_id","Source EUI", "Site EUI"]]
df_2019_temp.rename(columns={'Source EUI': 'Source EUI 2019', 'Site EUI': 'Site EUI 2019'}, inplace=True)
df_2019_temp.head()

    bl_id  Source EUI 2019  Site EUI 2019
0  B00005       206.481209     113.832299
1  B00011        31.465448      11.494336
2  B00022        44.936019      16.048578
3  B00026        12.045304       4.301894
4  B00028        72.763217      34.483230

In [98]:
df_temp_first = pd.merge(df_2017_temp,
                           df_2018_temp,
                           on = "bl_id",
                           how = "left")
df_temp_all = pd.merge(df_temp_first,
                           df_2019_temp,
                           on = "bl_id",
                           how = "left")
df_temp_all["Site EUI Change"] = (df_temp_all["Site EUI 2019"] - df_temp_all["Site EUI 2017"])/3
df_temp_all["Source EUI Change"] = (df_temp_all["Source EUI 2019"] - df_temp_all["Source EUI 2017"])/3
df_temp_all["Site EUI Percent Change"] = (df_temp_all["Site EUI Change"] / (df_temp_all[['Site EUI 2017', 'Site EUI 2018', 'Site EUI 2019']].mean(axis=1)))*100
df_temp_all["Source EUI Percent Change"] = (df_temp_all["Source EUI Change"] / (df_temp_all[['Source EUI 2017', 'Source EUI 2018', 'Source EUI 2019']].mean(axis=1)))*100
df_temp_all.head()

,bl_id,Source EUI 2017,Site EUI 2017,Source EUI 2018,Site EUI 2018,Source EUI 2019,Site EUI 2019,Site EUI Change,Source EUI Change,Site EUI Percent Change,Source EUI Percent Change
0,B00005,306.848545,156.077964,317.504576,164.396200,206.481209,113.832299,-14.081888,-33.455779,-9.727155,-12.080307
1,B00011,68.066331,25.051032,51.763754,19.139362,31.465448,11.494336,-4.518899,-12.200294,-24.345446,-24.191648
2,B00022,82.692379,29.532992,75.822962,27.079629,44.936019,16.048578,-4.494805,-12.585453,-18.557929,-18.557929
3,B00026,4.525676,1.616313,20.081284,7.171887,12.045304,4.301894,0.895194,2.506543,20.516137,20.516137
4,B00028,157.353138,73.023980,121.888117,58.739647,72.763217,34.483230,-12.846917,-28.196640,-23.182844,-24.030922

In [99]:
df_rate = pd.merge(df_temp_all,
                           df_buildings,
                           on = "bl_id",
                           how = "left")
df_rate.head()

,bl_id,Source EUI 2017,Site EUI 2017,Source EUI 2018,Site EUI 2018,Source EUI 2019,Site EUI 2019,Site EUI Change,Source EUI Change,Site EUI Percent Change,...,lot,lat,lon,sq_ft,property_type,agency_occupied,year_built,neighborhood,council_district,Property Type Code
0,B00005,306.848545,156.077964,317.504576,164.396200,206.481209,113.832299,-14.081888,-33.455779,-9.727155,...,1,39.29588,-76.610280,18144.00,"Warehouse, self storage",DGS,1945.0,Penn - Fallsway,11.0,11
1,B00011,68.066331,25.051032,51.763754,19.139362,31.465448,11.494336,-4.518899,-12.200294,-24.345446,...,1,39.28862,-76.618620,697620.00,"Public Assembly, Convention Center",Civic Centers,1960.0,Downtown,11.0,7
2,B00022,82.692379,29.532992,75.822962,27.079629,44.936019,16.048578,-4.494805,-12.585453,-18.557929,...,2,39.29556,-76.610280,11270.59,"Public Services, police",BCPD,NaN,Penn - Fallsway,11.0,1
3,B00026,4.525676,1.616313,20.081284,7.171887,12.045304,4.301894,0.895194,2.506543,20.516137,...,27,39.34462,-76.685455,56228.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1
4,B00028,157.353138,73.023980,121.888117,58.739647,72.763217,34.483230,-12.846917,-28.196640,-23.182844,...,11,39.25288,-76.617200,29314.00,"Public Services, police",BCPD,1965.0,Middle Branch - Reedbird Parks,10.0,1

In [100]:
df_rate.to_csv('RateChange.csv')

In [104]:
df_og_data = pd.merge(df_energy,
                           df_buildings,
                           on = "bl_id",
                           how = "left")
df_og_data.head()

,bl_id,building_name,address,utility,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,name,...,lot,lat,lon,sq_ft,property_type,agency_occupied,year_built,neighborhood,council_district,Property Type Code
0,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,12.0,2019.0,36551.0,1173.0,Baltimore City Police Northern District,...,009A,39.34304,-76.65236,25508.47,"Public Services, police",BCPD,2001.0,Woodberry,6.0,1
1,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,12.0,2019.0,11780.0,2966.0,Eastside Career Center,...,1,39.29973,-76.57500,27910.00,"Education, vocational",MOED,1955.0,Maidson- Eastend,NaN,2
2,B00022,Baltimore City Mounted Police Unit,411 Fallsway St,bge,2.119590e+09,12.0,2018.0,7301.0,0.0,Baltimore City Mounted Police Unit,...,2,39.29556,-76.61028,11270.59,"Public Services, police",BCPD,NaN,Penn - Fallsway,11.0,1
3,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,11.0,2019.0,33586.0,1151.0,Baltimore City Police Northern District,...,009A,39.34304,-76.65236,25508.47,"Public Services, police",BCPD,2001.0,Woodberry,6.0,1
4,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,11.0,2019.0,11420.0,2232.0,Eastside Career Center,...,1,39.29973,-76.57500,27910.00,"Education, vocational",MOED,1955.0,Maidson- Eastend,NaN,2

In [102]:
df_og_data.to_csv('OGData.csv')

In [106]:
df_all_data = pd.merge(df_energy,
                           df_temp_all,
                           on = "bl_id",
                           how = "left")
df_all_data.head()

,bl_id,building_name,address,utility,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,Source EUI 2017,Site EUI 2017,Source EUI 2018,Site EUI 2018,Source EUI 2019,Site EUI 2019,Site EUI Change,Source EUI Change,Site EUI Percent Change,Source EUI Percent Change
0,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,12.0,2019.0,36551.0,1173.0,283.156960,130.990116,237.313696,113.110669,189.114208,93.137678,-12.617479,-31.347584,-11.224235,-13.253207
1,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,12.0,2019.0,11780.0,2966.0,104.454378,64.463860,109.857716,72.034522,101.581345,68.765168,1.433769,-0.957678,2.095505,-0.909494
2,B00022,Baltimore City Mounted Police Unit,411 Fallsway St,bge,2.119590e+09,12.0,2018.0,7301.0,0.0,82.692379,29.532992,75.822962,27.079629,44.936019,16.048578,-4.494805,-12.585453,-18.557929,-18.557929
3,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,11.0,2019.0,33586.0,1151.0,283.156960,130.990116,237.313696,113.110669,189.114208,93.137678,-12.617479,-31.347584,-11.224235,-13.253207
4,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,11.0,2019.0,11420.0,2232.0,104.454378,64.463860,109.857716,72.034522,101.581345,68.765168,1.433769,-0.957678,2.095505,-0.909494

In [107]:
df_all_data2 = pd.merge(df_all_data,
                           df_buildings,
                           on = "bl_id",
                           how = "left")
df_all_data2.head()

,bl_id,building_name,address,utility,account,consump_month,consump_year,bge_kWh_used,bge_therms_used,Source EUI 2017,...,lot,lat,lon,sq_ft,property_type,agency_occupied,year_built,neighborhood,council_district,Property Type Code
0,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,12.0,2019.0,36551.0,1173.0,283.156960,...,009A,39.34304,-76.65236,25508.47,"Public Services, police",BCPD,2001.0,Woodberry,6.0,1
1,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,12.0,2019.0,11780.0,2966.0,104.454378,...,1,39.29973,-76.57500,27910.00,"Education, vocational",MOED,1955.0,Maidson- Eastend,NaN,2
2,B00022,Baltimore City Mounted Police Unit,411 Fallsway St,bge,2.119590e+09,12.0,2018.0,7301.0,0.0,82.692379,...,2,39.29556,-76.61028,11270.59,"Public Services, police",BCPD,NaN,Penn - Fallsway,11.0,1
3,B00035,Baltimore City Police Northern District,2201 West Cold Spring Lane,bge,3.275661e+09,11.0,2019.0,33586.0,1151.0,283.156960,...,009A,39.34304,-76.65236,25508.47,"Public Services, police",BCPD,2001.0,Woodberry,6.0,1
4,B08020,Eastside Career Center,3001 E Madison St,bge,5.884920e+09,11.0,2019.0,11420.0,2232.0,104.454378,...,1,39.29973,-76.57500,27910.00,"Education, vocational",MOED,1955.0,Maidson- Eastend,NaN,2